/** Реестр юнитов автоматизации ccapital.pro (источник правды для дашборда). */

export const BLOCKS = [
  { id: "publish", title: "Публикация и SEO", icon: "📡" },
  { id: "traffic", title: "Платный трафик", icon: "📊" },
  { id: "leads", title: "Лиды и коммуникации", icon: "📥" },
  { id: "social", title: "Контент-дистрибуция", icon: "📣" },
  { id: "product", title: "Клиентский продукт", icon: "🏛" },
  { id: "content", title: "Контент-план", icon: "🗂" },
];

export const UNITS = [
  {
    id: "deploy",
    block: "publish",
    name: "Deploy",
    does: "main → gh-pages, проверка live",
    goal: "Выкатить сайт за один шаг",
    trigger: "Ручной / workflow",
    io: "коммит → live ccapital.pro",
    health: "github_actions",
    action: "deploy",
  },
  {
    id: "indexnow",
    block: "publish",
    name: "IndexNow",
    does: "Пуш URL в Яндекс/Bing",
    goal: "Быстрая переиндексация",
    trigger: "Ручной / API",
    io: "URL → IndexNow 200/202",
    health: "indexnow",
    action: "indexnow_recent",
  },
  {
    id: "dzen_feed",
    block: "publish",
    name: "Dzen feed builder",
    does: "journal/feed.xml + content:encoded",
    goal: "RSS-импорт в Дзен (≥10 подписчиков)",
    trigger: "Скрипт / workflow",
    io: "HTML → feed.xml",
    health: "dzen_feed",
    action: "rebuild_dzen_feed",
  },
  {
    id: "dzen_extract",
    block: "publish",
    name: "Dzen text extractor",
    does: "HTML → /tmp/dzen/<slug>.json",
    goal: "Paste в редактор Дзена",
    trigger: "Ручной CLI",
    io: "journal HTML → JSON",
    health: "manual",
    action: null,
  },
  {
    id: "dzen_publisher",
    block: "publish",
    name: "Dzen publisher",
    does: "Браузерная автоматизация Draft.js",
    goal: "Посты до 10 подписчиков",
    trigger: "Ручной",
    io: "JSON → канал @charter_capital",
    health: "manual",
    action: null,
  },
  {
    id: "direct_import",
    block: "traffic",
    name: "Яндекс.Директ import",
    does: "build_import.py → CSV для Коммандера",
    goal: "Лиды с поиска (~5000₽/нед)",
    trigger: "Ручной",
    io: "ключи → 3 CSV",
    health: "direct_csv",
    action: "regenerate_direct",
  },
  {
    id: "forms_telegram",
    block: "leads",
    name: "Forms → Telegram",
    does: "forms-telegram.js + forms-proxy Worker",
    goal: "Мгновенная доставка заявок",
    trigger: "Submit формы",
    io: "форма → @ccapital_forms_bot",
    health: "forms_proxy",
    action: null,
  },
  {
    id: "ai_chat",
    block: "leads",
    name: "AI-чат «Артур»",
    does: "chat-widget + charter-chat Worker",
    goal: "Прогрев лида на сайте",
    trigger: "Виджет",
    io: "диалог → @ccapital_acces",
    health: "charter_chat",
    action: null,
  },
  {
    id: "tg_announce",
    block: "social",
    name: "Telegram-анонсы",
    does: "drafts/tg-*.md → @ccapital26",
    goal: "Трафик на журнал 2×/нед",
    trigger: "Ручной пост",
    io: "черновик → канал",
    health: "drafts_tg",
    action: null,
  },
  {
    id: "vc_ru",
    block: "social",
    name: "VC.ru лонгриды",
    does: "drafts/vc-ru-*.md",
    goal: "Экспертный бренд 2×/мес",
    trigger: "Ручной",
    io: "markdown → VC.ru",
    health: "drafts_vc",
    action: null,
  },
  {
    id: "stories",
    block: "social",
    name: "Stories генератор",
    does: "drafts/social/build_story.py",
    goal: "9:16 PNG для сторис",
    trigger: "Ручной",
    io: "шаблон → PNG",
    health: "manual",
    action: null,
  },
  {
    id: "reels",
    block: "social",
    name: "Reels / видео-бриф",
    does: "drafts/reels/*",
    goal: "AI-видео 1×/нед",
    trigger: "Ручной",
    io: "бриф → CapCut/Kling",
    health: "drafts_reels",
    action: null,
  },
  {
    id: "charter_flow",
    block: "product",
    name: "Charter Flow",
    does: "React/Vite клиентский дашборд сделок",
    goal: "Прозрачность для клиента",
    trigger: "Static deploy",
    io: "data.js → UI",
    health: "charter_flow_live",
    action: null,
  },
  {
    id: "acts_pdf",
    block: "product",
    name: "Acts PDF builder",
    does: "build-pdfs.sh → public/docs",
    goal: "PDF акты по сделке",
    trigger: "Ручной",
    io: "HTML → PDF",
    health: "manual",
    action: null,
  },
  {
    id: "anchor_map",
    block: "content",
    name: "Карта статей-якорей",
    does: "drafts/content-anchor-map.md",
    goal: "15 статей SEO + ИИ",
    trigger: "Редактирование",
    io: "план → journal HTML",
    health: "content_kanban",
    action: null,
  },
];
